In [1]:
import cv2
import mediapipe as mp
import numpy as np
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
cap = cv2.VideoCapture(0)
with mp_pose.Pose(min_detection_confidence=0.5, min_tracking_confidence=0.5) as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        # Recolor image to RGB
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
          
        # Make detection
        results = pose.process(image)
        
        # Recolor back to BGR
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)    
        landmarks = results.pose_landmarks.landmark
        
        # Render detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                mp_drawing.DrawingSpec(color=(1,2,1), thickness=5, circle_radius=1), 
                                mp_drawing.DrawingSpec(color=(1,66,230), thickness=5, circle_radius=1) 
                                 )         
        cv2.imshow('Mediapipe Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):    # If you click the q button, camera will shutdown.
            break

    cap.release()
    cv2.destroyAllWindows()

In [2]:
landmarks[mp_pose.PoseLandmark.LEFT_HEEL.value]  # which make senses, because my camera did not see my left heel.
# Therefore its visibility is almost 0.

x: 0.7527098655700684
y: 2.8504579067230225
z: 0.7524496912956238
visibility: 3.884515899699181e-05

In [3]:
landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value] # which make senses, because my camera saw my left shoulder.
# Therefore its visibility is almost 1.

x: 0.8110420107841492
y: 0.8623376488685608
z: -0.6066159009933472
visibility: 0.9916006326675415

In [4]:
landmarks[mp_pose.PoseLandmark.LEFT_EAR.value]

x: 0.6710669994354248
y: 0.5470360517501831
z: -0.9052830934524536
visibility: 0.9985768795013428

In [5]:
landmarks[mp_pose.PoseLandmark.RIGHT_EAR.value] 

x: 0.4827217161655426
y: 0.5527170300483704
z: -0.9392975568771362
visibility: 0.9993141889572144

In [6]:
image.shape   # our image has a shape (480, 640, 3)

(480, 640, 3)

In [7]:
def shaper(a):
    a[0] = a[0] * 480            #height
    a[1] = a[1] * 640            #weight
    a[2] = a[2] * 3 
    return a

In [8]:
shaper(image)

array([[[160, 224,  96],
        [ 64, 224, 128],
        [160,  32, 224],
        ...,
        [224, 192,   0],
        [  0, 224, 160],
        [160, 160,   0]],

       [[128, 128, 128],
        [  0,   0, 128],
        [128, 128, 128],
        ...,
        [128, 128,   0],
        [  0,   0,   0],
        [128,   0, 128]],

       [[119,  20,  38],
        [110,  20,  38],
        [ 98,  26,  41],
        ...,
        [ 70,  88,  14],
        [ 73,  85,  17],
        [ 76,  85,  23]],

       ...,

       [[129, 125,  50],
        [132, 128,  53],
        [133, 128,  53],
        ...,
        [253, 255, 192],
        [255, 255, 186],
        [255, 255, 184]],

       [[131, 124,  51],
        [133, 126,  53],
        [133, 126,  53],
        ...,
        [253, 255, 203],
        [254, 255, 198],
        [255, 255, 196]],

       [[131, 124,  51],
        [132, 125,  52],
        [131, 124,  51],
        ...,
        [252, 255, 208],
        [253, 255, 203],
        [254, 255, 201]]

In [9]:
pixel_image = shaper(image)
pixel_image

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[101,  60, 114],
        [ 74,  60, 114],
        [ 38,  78, 123],
        ...,
        [210,   8,  42],
        [219, 255,  51],
        [228, 255,  69]],

       ...,

       [[129, 125,  50],
        [132, 128,  53],
        [133, 128,  53],
        ...,
        [253, 255, 192],
        [255, 255, 186],
        [255, 255, 184]],

       [[131, 124,  51],
        [133, 126,  53],
        [133, 126,  53],
        ...,
        [253, 255, 203],
        [254, 255, 198],
        [255, 255, 196]],

       [[131, 124,  51],
        [132, 125,  52],
        [131, 124,  51],
        ...,
        [252, 255, 208],
        [253, 255, 203],
        [254, 255, 201]]

In [10]:
pixel_image.shape

(480, 640, 3)

In [11]:
landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value]

x: 0.8110420107841492
y: 0.8623376488685608
z: -0.6066159009933472
visibility: 0.9916006326675415

In [12]:
a = landmarks[mp_pose.PoseLandmark.LEFT_SHOULDER.value]
a_ = shaper(np.array((a.x, a.y, a.z)))

In [13]:
a_

array([389.30016518, 551.89609528,  -1.8198477 ])

In [14]:
landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value]  # yeap, visible!

x: 0.34887081384658813
y: 0.8682756423950195
z: -0.6183449029922485
visibility: 0.9936127066612244

In [15]:
b = landmarks[mp_pose.PoseLandmark.RIGHT_SHOULDER.value]
b_ = shaper(np.array((b.x, b.y, b.z)))

In [16]:
b_

array([167.45799065, 555.69641113,  -1.85503471])

In [17]:
for no, lndmrk in enumerate(mp_pose.PoseLandmark):
    print(no, end = " >>>>>  ")
    print(str(lndmrk).split(".",1)[1])

0 >>>>>  NOSE
1 >>>>>  LEFT_EYE_INNER
2 >>>>>  LEFT_EYE
3 >>>>>  LEFT_EYE_OUTER
4 >>>>>  RIGHT_EYE_INNER
5 >>>>>  RIGHT_EYE
6 >>>>>  RIGHT_EYE_OUTER
7 >>>>>  LEFT_EAR
8 >>>>>  RIGHT_EAR
9 >>>>>  MOUTH_LEFT
10 >>>>>  MOUTH_RIGHT
11 >>>>>  LEFT_SHOULDER
12 >>>>>  RIGHT_SHOULDER
13 >>>>>  LEFT_ELBOW
14 >>>>>  RIGHT_ELBOW
15 >>>>>  LEFT_WRIST
16 >>>>>  RIGHT_WRIST
17 >>>>>  LEFT_PINKY
18 >>>>>  RIGHT_PINKY
19 >>>>>  LEFT_INDEX
20 >>>>>  RIGHT_INDEX
21 >>>>>  LEFT_THUMB
22 >>>>>  RIGHT_THUMB
23 >>>>>  LEFT_HIP
24 >>>>>  RIGHT_HIP
25 >>>>>  LEFT_KNEE
26 >>>>>  RIGHT_KNEE
27 >>>>>  LEFT_ANKLE
28 >>>>>  RIGHT_ANKLE
29 >>>>>  LEFT_HEEL
30 >>>>>  RIGHT_HEEL
31 >>>>>  LEFT_FOOT_INDEX
32 >>>>>  RIGHT_FOOT_INDEX
